[2021-02-05 10:27:45,019] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2019-01-17T18:00:00+00:00 [queued]>
[2021-02-05 10:27:45,026] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_events 2019-01-17T18:00:00+00:00 [queued]>
[2021-02-05 10:27:45,026] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 10:27:45,026] {taskinstance.py:881} INFO - Starting attempt 1 of 4
[2021-02-05 10:27:45,026] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 10:27:45,029] {taskinstance.py:901} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-01-17T18:00:00+00:00
[2021-02-05 10:27:45,034] {standard_task_runner.py:54} INFO - Started process 93240 to run task
[2021-02-05 10:27:45,064] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Stage_events', '2019-01-17T18:00:00+00:00', '--job_id', '863', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmpfo54e5ap']
[2021-02-05 10:27:45,065] {standard_task_runner.py:78} INFO - Job 863: Subtask Stage_events
[2021-02-05 10:27:45,082] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Stage_events 2019-01-17T18:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-05 10:27:45,135] {stage_redshift.py:57} INFO - Clearing data from destination Redshift table: staging_events
[2021-02-05 10:27:45,137] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-05 10:27:46,469] {dbapi_hook.py:176} INFO - DELETE FROM staging_events
[2021-02-05 10:27:47,093] {stage_redshift.py:60} INFO - Copying data from S3 to Redshift
[2021-02-05 10:27:47,104] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-05 10:27:48,413] {dbapi_hook.py:176} INFO - 
        COPY staging_events
        FROM 's3://udacity-dend/log_data'
        ACCESS_KEY_ID 'AKIA2IMWSL5GKAQJ27TS'
        SECRET_ACCESS_KEY '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'
        IGNOREHEADER 1
        DELIMITER ','
    
[2021-02-05 10:27:48,917] {taskinstance.py:1150} ERROR - Load into table 'staging_events' failed.  Check 'stl_load_errors' system table for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/trevorransom/Documents/01 Coding/03 Data Engineering/Udacity/05 Airflow/plugins/operators/stage_redshift.py", line 71, in execute
    redshift.run(formatted_sql)
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.InternalError_: Load into table 'staging_events' failed.  Check 'stl_load_errors' system table for details.

[2021-02-05 10:27:48,923] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_events, execution_date=20190117T180000, start_date=20210205T082745, end_date=20210205T082748
[2021-02-05 10:27:50,035] {local_task_job.py:102} INFO - Task exited with return code 1
