[2021-02-04 17:08:12,031] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Create_tables 2019-01-16T16:00:00+00:00 [queued]>
[2021-02-04 17:08:12,036] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Create_tables 2019-01-16T16:00:00+00:00 [queued]>
[2021-02-04 17:08:12,036] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 17:08:12,036] {taskinstance.py:881} INFO - Starting attempt 2 of 4
[2021-02-04 17:08:12,036] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-04 17:08:12,039] {taskinstance.py:901} INFO - Executing <Task(PostgresOperator): Create_tables> on 2019-01-16T16:00:00+00:00
[2021-02-04 17:08:12,043] {standard_task_runner.py:54} INFO - Started process 38182 to run task
[2021-02-04 17:08:12,074] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Create_tables', '2019-01-16T16:00:00+00:00', '--job_id', '678', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmp8ncto5qr']
[2021-02-04 17:08:12,075] {standard_task_runner.py:78} INFO - Job 678: Subtask Create_tables
[2021-02-04 17:08:12,092] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Create_tables 2019-01-16T16:00:00+00:00 [running]> on host trevors-macbook-air.local
[2021-02-04 17:08:12,101] {taskinstance.py:1150} ERROR - sql_create_tables.sql
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 965, in _run_raw_task
    self.render_templates(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1424, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 719, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 726, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 753, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql_create_tables.sql
[2021-02-04 17:08:12,103] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Create_tables, execution_date=20190116T160000, start_date=20210204T150812, end_date=20210204T150812
[2021-02-04 17:08:17,057] {local_task_job.py:102} INFO - Task exited with return code 1
