[2021-02-05 12:28:03,150] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs 2021-01-14T02:00:00+00:00 [queued]>
[2021-02-05 12:28:03,157] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Stage_songs 2021-01-14T02:00:00+00:00 [queued]>
[2021-02-05 12:28:03,157] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 12:28:03,157] {taskinstance.py:881} INFO - Starting attempt 1 of 4
[2021-02-05 12:28:03,157] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-05 12:28:03,160] {taskinstance.py:901} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2021-01-14T02:00:00+00:00
[2021-02-05 12:28:03,164] {standard_task_runner.py:54} INFO - Started process 77426 to run task
[2021-02-05 12:28:03,195] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'udac_example_dag', 'Stage_songs', '2021-01-14T02:00:00+00:00', '--job_id', '1143', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/udac_example_dag.py', '--cfg_path', '/var/folders/ys/hb038j3904j77l4dkb4zk2ym0000gq/T/tmp35m7yxvv']
[2021-02-05 12:28:03,196] {standard_task_runner.py:78} INFO - Job 1143: Subtask Stage_songs
[2021-02-05 12:28:03,213] {logging_mixin.py:112} INFO - Running <TaskInstance: udac_example_dag.Stage_songs 2021-01-14T02:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-05 12:28:03,266] {stage_redshift.py:59} INFO - Clearing data from destination Redshift table: staging_songs
[2021-02-05 12:28:03,268] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-05 12:28:04,590] {dbapi_hook.py:176} INFO - DELETE FROM staging_songs
[2021-02-05 12:28:05,315] {stage_redshift.py:62} INFO - Copying data from S3 to Redshift
[2021-02-05 12:28:05,322] {base_hook.py:89} INFO - Using connection to: id: redshift. Host: redshift-cluster-airflow.ca3iipyjqhur.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-02-05 12:28:06,630] {dbapi_hook.py:176} INFO - 
        COPY staging_songs
        FROM 's3://udacity-dend/song_data/A/A/A'
        ACCESS_KEY_ID 'AKIA2IMWSL5GKAQJ27TS'
        SECRET_ACCESS_KEY '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'
        REGION 'us-west-2'
        JSON '1'
        COMPUPDATE OFF
    
[2021-02-05 12:28:07,160] {taskinstance.py:1150} ERROR - S3 path "1" has invalid format.
DETAIL:  
  -----------------------------------------------
  error:  S3 path "1" has invalid format.
  code:      8001
  context:   Parsing S3 Bucket
  query:     413
  location:  s3_utility.cpp:131
  process:   padbmaster [pid=16398]
  -----------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/trevorransom/Documents/01 Coding/03 Data Engineering/Udacity/05 Airflow/plugins/operators/stage_redshift.py", line 74, in execute
    redshift.run(formatted_sql)
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi_hook.py", line 177, in run
    cur.execute(s)
psycopg2.errors.InternalError_: S3 path "1" has invalid format.
DETAIL:  
  -----------------------------------------------
  error:  S3 path "1" has invalid format.
  code:      8001
  context:   Parsing S3 Bucket
  query:     413
  location:  s3_utility.cpp:131
  process:   padbmaster [pid=16398]
  -----------------------------------------------


[2021-02-05 12:28:07,169] {taskinstance.py:1187} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Stage_songs, execution_date=20210114T020000, start_date=20210205T102803, end_date=20210205T102807
[2021-02-05 12:28:08,159] {local_task_job.py:102} INFO - Task exited with return code 1
